### ISSUE TITLE
`rand.Rand` is not safe for concurrent use

### ISSUE THREAD

**Issue by justinrixx** [PuerkitoBio/rehttp#12]
I recently learned that random sources from `math/rand` are not safe for concurrent use. This is relevant to this package as the global `PRNG` (found in `rehttp.go`) does not have a mutex to guard against possible runtime panics.

[Relevant note from the docs](https://pkg.go.dev/math/rand#NewSource):

> Unlike the default [Source](https://pkg.go.dev/math/rand#Source) used by top-level functions, this source is not safe for concurrent use by multiple goroutines.

I have not attempted to reproduce a panic in this package directly, but I have found that they do occur when generating pseudorandom numbers concurrently:

```go
package main

import (
	"fmt"
	"math/rand"
	"sync"
	"time"
)

var src = rand.New(rand.NewSource(time.Now().UnixNano()))

func main() {
	var wg sync.WaitGroup

  for i := 0; i < 10; i++ {
		wg.Add(1)
		go func() {
			genRandom()
			wg.Done()
		}()
	}

	wg.Wait()	
  fmt.Println("done")
}

func genRandom() {
	for i := 0; i < 100_000_000; i++ {
		src.Intn(100)
	}
}
```

**Comment by justinrixx** [comment]
My thoughts on options for a potential fix:

- Add a global mutex and put all random generation that uses the global source inside mutex lock / unlocks (this could still panic if some other package in an app uses the global PRNG from this package without locking a mutex)
- Switch to using the global random source: instead of using `PRNG.Int63n` ([as in this code](https://github.com/PuerkitoBio/rehttp/blob/master/rehttp.go#L267)), use `rand.Int63n` ([docs](https://pkg.go.dev/math/rand#Int63n)).

This is maybe a little bit tricky because the global `PRNG` is a public field that other packages may be relying on, so if you move to using `math/rand`'s global random source you'll have to decide what to do with the global `PRNG`.

Also, if you choose to go with `math/rand`'s global random source, depending on what go versions you want to target, you'll need to call `rand.Seed` ([docs](https://pkg.go.dev/math/rand#Seed)) before generating numbers. Go 1.20+ already does this, but for older versions you probably don't want to skip the seed step. I think this could be done pretty cleanly in an `init` function:

```go
func init() {
   rand.Seed(time.Now().UnixNano())
}
```

**Comment by mna** [comment]
Hello Justin,

Thanks for raising this, that's a great catch! I read a bit on the `math/rand` issues (see https://github.com/golang/go/issues/21393 and the linked proposals towards the end), looks like how this stdlib package will evolve is still TBD. I don't love the idea of using the `rand` package's global source without a way out... The `PRNG` variable is used for one thing only in all `rehttp`, and that's for the exponential backoff delay, and it uses a single method of the `rand.Rand` type, `Int63n`. 

I think it'd be reasonable to deprecate the `PRNG` variable altogether so it is unused starting at the next version, and require instead the caller to provide a `func (n int64) int64` that must be safe for concurrent use and that returns a non-negative number in the [0,n) interval. It could use the `rand.Int63n` function as default (which is safe for concurrent use), but with the option to use a caller-controlled random source instead.

What do you think, does that make sense to you?

Thanks,
Martin

**Comment by justinrixx** [comment]
Thanks for linking that issue, I hadn't seen it before.

Go 1.22 introduced `math/rand/v2`, but it seems to have the same design when it comes to concurrency (the top-level source is concurrency-safe, but sources created with `rand.NewChaCha8`, `rand.NewPCG`, etc are not) ([docs](https://pkg.go.dev/math/rand/v2)). That leads me to think it won't be changing any time soon.

> require instead the caller to provide a `func (n int64) int64` that must be safe for concurrent use and that returns a non-negative number in the [0,n) interval

I suspect most users will be fine with the default `rand.Int63n` generator, so IMO that should be the default behavior and users should not need to change the way they use the package (besides to stop using `PRNG` if they are currently). The issue you linked above though does bring up a good point about other packages being able to reseed the global source to something deterministic, which is a good reason to allow for the behavior to be overridden.

Another reason a user might want to override the random number generator is to reduce mutex contention for number generation. If there's just a single mutex (as in the global random source), it could become a bottleneck. But a user could create a sort of random source pool of say 10 random sources, along with a mutex for each plus an atomic counter. Every time a request is made to generate a new random number, they could atomically increment the counter, then generate the random number using one of the random sources (`srcs[counter % len(sources)]`), being sure to lock and unlock the mutex corresponding to the random source. (I have not benchmarked this idea, so it may not make any sense to do, but it still illustrates that your approach adds flexibility).

All that to say, I like your idea of allowing the caller to provide an override. I would add it as a new optional field on `Transport`. If it's `nil`, fall back to `rand.Int64n`. If it's non-nil, use it.

**Comment by mna** [comment]
> Go 1.22 introduced `math/rand/v2`

Ah yeah, now that you mention it I remember reading about it. 

> That leads me to think it won't be changing any time soon.

Agree with you.

> I like your idea of allowing the caller to provide an override. I would add it as a new optional field on Transport. If it's nil, fall back to rand.Int63n. If it's non-nil, use it.

Yeah adding it on Transport makes a lot of sense, would be nice to get rid of the package-level state. Sounds like a plan, would you be interested in contributing such a PR?

**Comment by justinrixx** [comment]
Hmm I just realized putting it on `Transport` probably won't work. The usage is in the `ExpJitterDelay` function, which is a helper that does not have a reference to the `Transport`.

Getting a custom random source to that function would require changing its signature, a breaking change.

Maybe the best way forward is:

- update `ExpJitterDelay` to use `rand.Int64n`
- add a new `ExpJitterDelayCustomSrc` with signature `func ExpJitterDelay(base, max time.Duration, src func (n int64) int64) DelayFn`

**Comment by mna** [comment]
> The usage is in the ExpJitterDelay function, which is a helper that does not have a reference to the Transport.

Ah right... Yeah makes sense to add a new helper function then. Only thing, I think I'd name it `ExpJitterDelayWithRand` because it's not so much a "source" anymore it's just a function that returns a random number. And we can document that `ExpJitterDelay` uses `rand.Int63n` and mark `PRNG` as deprecated and unused by the package.
